server:
  port: 5100
spring:
  application:
    name: product-command-app

  # Config server
  cloud:
    config:
      enabled: false

  # Database connection
  datasource:
    url: jdbc:mysql://localhost:3306/ecm_products_db?useSSL=true
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
