spring:
  application:
    name: api-gateway
  server:
    port: 9999
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

