server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/feehaam/ecms-config.git
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
